# Generated by Django 5.2.9 on 2025-12-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0002_alter_customuser_bot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bot_exp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
