# Generated by Django 5.2.9 on 2025-12-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0003_customuser_bot_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bot_exp',
            field=models.CharField(default='today'),
        ),
    ]
