# Generated by Django 5.2.9 on 2025-12-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0004_alter_customuser_bot_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_ad_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_ad_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bot_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bot_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
