# Generated by Django 5.2.9 on 2025-12-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0005_customuser_daily_ad_count_customuser_daily_ad_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_ver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ver_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
