# Generated by Django 5.2.9 on 2025-12-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0006_customuser_email_ver_customuser_ver_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attemps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
