# Generated by Django 5.2.9 on 2025-12-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0007_customuser_attemps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='attemps',
            new_name='attempts',
        ),
    ]
