# Generated by Django 5.2.9 on 2025-12-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0008_rename_attemps_customuser_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ver_code',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
